"""add post table

Revision ID: 314e6793fe82
Revises: 3d6e32b49e9a
Create Date: 2019-04-19 19:03:24.717316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314e6793fe82'
down_revision = '3d6e32b49e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
